drop table edu_dwd.fact_customer_clue1;
CREATE TABLE IF NOT EXISTS edu_dwd.fact_customer_clue1 (
id int COMMENT 'customer_clue_id',
--   create_date_time STRING COMMENT '创建时间',
--   update_date_time STRING COMMENT '最后更新时间',
--   deleted STRING COMMENT '是否被删除（禁用）',
--   customer_id int COMMENT '客户id',
customer_relationship_id int COMMENT '客户关系id',
--   session_id STRING COMMENT '七陌会话id',
--   sid STRING COMMENT '访客id',
--   status STRING COMMENT '状态（undeal待领取 deal 已领取 finish 已关闭 changePeer 已流转）',
--   users STRING COMMENT '所属坐席',
--   create_time STRING COMMENT '七陌创建时间',
--   platform STRING COMMENT '平台来源 （pc-网站咨询|wap-wap咨询|sdk-app咨询|weixin-微信咨询）',
--   s_name STRING COMMENT '用户名称',
--   seo_source STRING COMMENT '搜索来源',
--   seo_keywords STRING COMMENT '关键字',
--   ip STRING COMMENT 'IP地址',
--   referrer STRING COMMENT '上级来源页面',
--   from_url STRING COMMENT '会话来源页面',
--   landing_page_url STRING COMMENT '访客着陆页面',
--   url_title STRING COMMENT '咨询页面title',
--   to_peer STRING COMMENT '所属技能组',
--   manual_time STRING COMMENT '人工开始时间',
--   begin_time STRING COMMENT '坐席领取时间 ',
--   reply_msg_count int COMMENT '客服回复消息数',
--   total_msg_count int COMMENT '消息总数',
--   msg_count int COMMENT '客户发送消息数',
--   comment STRING COMMENT '备注',
--   finish_reason STRING COMMENT '结束类型',
--   finish_user STRING COMMENT '结束坐席',
--   end_time STRING COMMENT '会话结束时间',
--   platform_description STRING COMMENT '客户平台信息',
--   browser_name STRING COMMENT '浏览器名称',
--   os_info STRING COMMENT '系统名称',
--   area STRING COMMENT '区域',
--   country STRING COMMENT '所在国家',
--   province STRING COMMENT '省',
--   city STRING COMMENT '城市',
creator int COMMENT '创建人',
--   name STRING COMMENT '客户姓名',
--   idcard STRING COMMENT '身份证号',
--   phone STRING COMMENT '手机号',
--   itcast_school_id int COMMENT '校区Id',
--   itcast_school STRING COMMENT '校区',
--   itcast_subject_id int COMMENT '学科Id',
--   itcast_subject STRING COMMENT '学科',
--   wechat STRING COMMENT '微信',
--   qq STRING COMMENT 'qq号',
--   email STRING COMMENT '邮箱',
--   gender STRING COMMENT '性别',
--   level STRING COMMENT '客户级别',
--   origin_type STRING COMMENT '数据来源渠道',
--   information_way STRING COMMENT '资讯方式',
--   working_years STRING COMMENT '开始工作时间',
--   technical_directions STRING COMMENT '技术方向',
--   customer_state STRING COMMENT '当前客户状态',
--   valid STRING COMMENT '该线索是否是网资有效线索',
--   anticipat_signup_date STRING COMMENT '预计报名时间',
--   clue_state STRING COMMENT '线索状态',
--   scrm_department_id int COMMENT 'SCRM内部部门id',
--   superior_url STRING COMMENT '诸葛获取上级页面URL',
--   superior_source STRING COMMENT '诸葛获取上级页面URL标题',
--   landing_url STRING COMMENT '诸葛获取着陆页面URL',
--   landing_source STRING COMMENT '诸葛获取着陆页面URL来源',
--   info_url STRING COMMENT '诸葛获取留咨页URL',
--   info_source STRING COMMENT '诸葛获取留咨页URL标题',
--   origin_channel STRING COMMENT '投放渠道',
--   course_id int COMMENT '课程编号',
--   course_name STRING COMMENT '课程名称',
--   zhuge_session_id STRING COMMENT 'zhuge会话id',
--   is_repeat int COMMENT '是否重复线索(手机号维度) 0:正常 1：重复',
--   tenant int COMMENT '租户id',
--   activity_id STRING COMMENT '活动id',
--   activity_name STRING COMMENT '活动名称',
--   follow_type int COMMENT '分配类型，0-自动分配，1-手动分配，2-自动转移，3-手动单个转移，4-手动批量转移，5-公海领取',
--   shunt_mode_id int COMMENT '匹配到的技能组id',
--   shunt_employee_group_id int COMMENT '所属分流员工组',
clue_state_stat STRING COMMENT '线索状态,1为新客户新线索,0为老客户新线索,-1为无效数据',
end_date string comment '有效时间'
)comment '客户关系表'
PARTITIONED BY(start_date string)
clustered by(customer_relationship_id) sorted by(customer_relationship_id) into 10 buckets
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
stored as orc TBLPROPERTIES ('orc.compress'='SNAPPY');






SET hive.exec.dynamic.partition=true;
SET hive.exec.dynamic.partition.mode=nonstrict;
set hive.exec.max.dynamic.partitions.pernode=10000;
set hive.exec.max.dynamic.partitions=100000;
set hive.exec.max.created.files=150000;
--hive压缩
set hive.exec.compress.intermediate=true;
set hive.exec.compress.output=true;
--写入时压缩生效
set hive.exec.orc.compression.strategy=COMPRESSION;

set mapreduce.map.speculative=false;
set mapreduce.reduce.speculative=false;
set hive.mapred.reduce.tasks.speculative.execution=false;
INSERT into edu_dwd.fact_customer_clue1 partition(start_date)
SELECT
id,
--     create_date_time,
--     update_date_time,
--     deleted,
--     customer_id,
customer_relationship_id,
--     session_id,
--     sid,
--     status,
--     'users',
--     create_time,
--     platform,
--     s_name,
--     seo_source,
--     seo_keywords,
--     ip,
--     referrer,
--     from_url,
--     landing_page_url,
--     url_title,
--     to_peer,
--     manual_time,
--     begin_time,
--     reply_msg_count,
--     total_msg_count,
--     msg_count,
--     comment,
--     finish_reason,
--     finish_user,
--     end_time,
--     platform_description,
--     browser_name,
--     os_info,
--     area,
--     country,
--     province,
--     city,
creator,
--     name,
--     idcard,
--     phone,
--     itcast_school_id,
--     itcast_school,
--     itcast_subject_id,
--     itcast_subject,
--     wechat,
--     qq,
--     email,
--     gender,
--     level,
--     origin_type,
--     information_way,
--     working_years,
--     technical_directions,
--     customer_state,
--     valid,
--     anticipat_signup_date,
--     clue_state,
--     scrm_department_id,
--     superior_url,
--     superior_source,
--     landing_url,
--     landing_source,
--     info_url,
--     info_source,
--     origin_channel,
--     course_id,
--     course_name,
--     zhuge_session_id,
--     is_repeat,
--     tenant,
--     activity_id,
--     activity_name,
--     follow_type,
--     shunt_mode_id,
--     shunt_employee_group_id,
case when clue_state='VALID_NEW_CLUES'
    then 1
    when clue_state='VALID_PUBLIC_NEW_CLUE'
    then 0
    else -1
end clue_state_stat,
'9999-99-99' as end_date,
    if(update_date_time is null or update_date_time='',substr(create_date_time,1,10),substr(update_date_time,1,10)) as start_date
from edu_ods.customer_clue where deleted = 'false';